### ISSUE TITLE
SPFX webpart

### ISSUE THREAD

**Issue by lbenassi** [fredupstair/react-cs-images-suggestion#1]
Hi @fredupstair I try to implement this solution but I'm not expert on SPFX webpart.
So I don't understand how to implement the web part that allows me to drag and drop the image.
How can I try to implement this part in an easier or alternative way?
Thanks.
Lorenzo

**Comment by fredupstair** [comment]
Hi @lbenassi what do you need exactly? :) Did you try to follow MD instructions? Do you need to implements react-cs-images-suggestion or a spfx webpart with a drop zone ?

**Comment by lbenassi** [comment]
Hi, yes I followed the MD instructions and with the help of rasper87 tutorial I have reproduced a similar flow to tag the new image saved in a specific folder (I don't understand because in your flow you have placed 2times the step Analyze image in sequence, how do you set up this steps?) and this flow works properly, but I am unable to implement a spfx webpart with a drop zone (I never used SPFX), any suggestions? Thanks

**Comment by fredupstair** [comment]
Hi @lbenassi thanks for the heads up, it's wrong. There is only an Analyze image step. I'll update the MD.
About SPFx developoment, you can start with this tutorial https://docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part and before you can create your environment on SharePoint online following this tutorial https://docs.microsoft.com/en-us/sharepoint/dev/spfx/set-up-your-developer-tenant 
Cheers,
Federico

**Comment by fredupstair** [comment]
@lbenassi flow is now fixed.
Cheers.
